name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3']
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        working-directory: ./
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        working-directory: ./
        run: composer install --prefer-dist --no-progress

      - name: Check coding standard
        working-directory: ./
        run: ./vendor/bin/phpcs --standard=phpcs.xml

      - name: Run static analysis
        uses: php-actions/phpstan@v3.0.3
        with:
          configuration: ./phpstan.neon

      - name: Run test suites
        working-directory: ./
        run: |
          mkdir code-coverage-php-html-${{ matrix.php-versions }}
          XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit.xml --coverage-clover code-coverage-php-clover-${{ matrix.php-versions }}.xml --coverage-html code-coverage-php-html-${{ matrix.php-versions }}

      - name: Upload code coverage report to GH
        uses: actions/upload-artifact@v4.5.0
        with:
          name: code-coverage-php-html-${{ matrix.php-versions }}
          path: ./code-coverage-php-html-${{ matrix.php-versions }}
          retention-days: 7

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./code-coverage-php-clover-${{ matrix.php-versions }}.xml
